# Changes here will be overwritten by Copier
AnswerStrategy: minimum
Authors: Abel Soares Siqueira <abel.s.siqueira@gmail.com> and contributors
JuliaIndentation: 2
JuliaMinVersion: '1.6'
License: MIT
LicenseCopyrightHolders: Abel Soares Siqueira
PackageName: BestieMinimum
PackageOwner: JuliaBesties
PackageUUID: 911d942b-976d-5ead-b2b6-c499ef4f1d7c
_commit: v0.12.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
